appName: crewmeister
replicaCount: 2

image:
  repository: docker.io/${DOCKER_USERNAME}/crewmeister-challenge
  tag: latest

containerPort: 8080

database:
  username: "root"
  password: "root"
  url: jdbc:mysql://mysql-service:3306/challenge

ingressHost: crewmeister.local
servicePort: 80
