appName: crewmeister
replicaCount: 2

image:
  repository: docker.io/richie001/crewmeister-challenge
  tag: latest

containerPort: 8080

database:
  username: '{{ .Values.dbUser | default "root" }}'
  password: '{{ .Values.dbPassword | default "root" }}'
  url: jdbc:mysql://mysql-service:3306/challenge

ingressHost: crewmeister.local
servicePort: 80
