appName: crewmeister
replicaCount: 2

image:
  repository: docker.io/richie001/crewmeister-challenge
  tag: latest

containerPort: 8080

database:
  url: jdbc:mysql://crewmeister-mysql:3306/challenge

ingressHost: crewmeister.local
servicePort: 80

mysql:
  enabled: true
  auth:
    rootPassword: "root"
    database: "challenge"
