appName: crewmeister
replicaCount: 2

image:
  repository: docker.io/richie001/crewmeister-challenge
  tag: latest

containerPort: 8080

database:
  username: "{{ .Values.dbUser | default "root" | b64enc }}"
  password: "{{ .Values.dbPassword | default "root" | b64enc }}"
  url: jdbc:mysql://mysql-service:3306/challenge

ingressHost: crewmeister.local
servicePort: 80
